version: '2'
services:
  mysql-master:
    image: reg.chiq-cloud.com/arm64v8/mysql:5.7.27
    container_name: supermap.mysql-master
    networks:
      - one-window
    environment:
      - MYSQL_ROOT_PASSWORD=eVoATqQM1VL4ysos
      - TZ=Asia/Shanghai
    volumes:
      # 数据库配置
      #- /root/mianyang/infrastructure/mysql/config:/etc/mysql
      - mysql_master_data:/var/lib/mysql
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=+8:00
    privileged: true
    restart: always
  # influxdb: https://hub.docker.com/_/influxdb
  influxdb:
    image: reg.chiq-cloud.com/arm64v8/influxdb:1.7.9
    container_name: supermap.influxdb
    environment:
      - TZ=Asia/Shanghai
    networks:
      - one-window
    volumes:
      - influxdb_data:/var/lib/influxdb
      - influxdb_data:/data/db
    ports:
      - 8286:8086
    restart: always
  mongo:
    image: reg.chiq-cloud.com/arm64v8/mongo:3
    container_name: supermap.mongo
    environment:
      - TZ=Asia/Shanghai
    networks:
      - one-window
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    ports:
      - 27017:27017
    restart: always
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
  elasticsearch:
    image: reg.chiq-cloud.com/arm64v8/elasticsearch-oss:6.7.0
    container_name: supermap.elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - ES_JAVA_OPTS=-Xms10240m -Xmx10240m
      - discovery.type=single-node
      - TZ=Asia/Shanghai
    networks:
      - one-window
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    restart: always
  rabbitmq:
    image: reg.chiq-cloud.com/arm64v8/rabbitmq:3.8-management
    container_name: supermap.rabbitmq
    privileged: true
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmqpassword
      - TZ=Asia/Shanghai
    networks:
      - one-window
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
  # redis
  redis:
    image: reg.chiq-cloud.com/arm64v8/redis:5.0.6
    container_name: supermap.redis
    environment:
      - TZ=Asia/Shanghai
    networks:
      - one-window
    privileged: true
    command: --requirepass "redispassword" --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    restart: always
networks:
  one-window:
    external:
      name: one-window
volumes:
  mysql_master_data:
    external: true
  influxdb_data:
    external: true
  mongo_data:
    external: true
  mongo_config:
    external: true
  elasticsearch_data:
    external: true
  rabbitmq_data:
    external: true
  redis_data:
    external: true

