spring:
  application:
    name: eureka-server-1

server:
  port: 10001

eureka:
  instance:
    hostname: eureka-server-1
    instance-id: eureka-server-1
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:10001/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
    peer-eureka-nodes-update-interval-ms: 10001

## 可以依据不同配置，启动多个 eureka server 实例

