version: '3'
# 绵阳一窗受理项目，日志收集环境的部署
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    image: mongo:3
    container_name: supermap.mongo
    volumes:
      - mongo_data:/data/db
    env_file:
      - env/common-environment.env
    restart: always
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.2
    container_name: supermap.elasticsearch
    volumes:
      - es_data:/usr/share/elasticsearch/data
    env_file:
      - env/common-environment.env
      - env/elasticsearch.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - 9200:9200
    restart: always
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:3.1
    container_name: supermap.garylog
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
      - ./config/graylog:/usr/share/graylog/data/config
    env_file:
      - env/common-environment.env
      - env/garylog.env
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    restart: always
    depends_on:
      - mongo
      - elasticsearch
networks:
  default:
    external:
      name: one-window
volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_journal:
    driver: local