version: '3'
# 绵阳一窗受理项目，基础环境的部署
services:
  # mysql: mysql主节点（待升级为 8.0）https://hub.docker.com/_/mysql
  mysql-master:
    image: mysql:5.7
    container_name: supermap.mysql-master
    env_file:
      - env/common-environment.env
      - env/mysql-master.env
    volumes:
      # 数据库配置
      #- /root/mianyang/infrastructure/mysql/config:/etc/mysql
      - mysql_master_data:/var/lib/mysql
    ports:
      - 3306:3306
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--default-time-zone=+8:00'
    privileged: true
    restart: always
  # nacos：https://hub.docker.com/r/nacos/nacos-server
  nacos:
    image: nacos/nacos-server:latest
    container_name: supermap.nacos
    env_file:
      - env/common-environment.env
      - env/nacos.env
    volumes:
      - ./logs/nacos/:/home/nacos/logs
      - ./config/nacos/nacos-custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - 8848:8848
      - 9555:9555
    depends_on:
      - mysql-master
    restart: always
  # redis
  redis:
    image: redis:5.0
    container_name: supermap.redis
    privileged: true
    command:
      - '--requirepass "redispassword"'
      - '--appendonly yes'
    volumes:
      - redis_data:/data
    env_file:
      - ./env/common-environment.env
    ports:
      - 6379:6379
    restart: always
  # rabbitmq
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: supermap.rabbitmq
    privileged: true
    env_file:
      - ./env/common-environment.env
      - ./env/rabbitmq.env
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
  #sentinel-dashboard：https://hub.docker.com/r/bladex/sentinel-dashboard
  sentinel-dashboard:
    image: bladex/sentinel-dashboard:1.7.0
    container_name: supermap.sentinel-dashboard
    volumes:
      - ./logs/sentinel:/root/logs
    env_file:
      - ./env/common-environment.env
      - ./env/sentinel-dashboard.env
    ports:
      - 8858:8858
      - 8718:8718
      - 8719:8719
    restart: always
  #elasticsearch-hd
  elasticsearch-hd:
    image: containerize/elastichd
    container_name: supermap.elasticsearch-hd
    env_file:
      - ./env/common-environment.env
    ports:
      - 9800:9800
    restart: always
  #zipkin
  zipkin:
    image: openzipkin/zipkin:2.18
    container_name: supermap.zipkin
    env_file:
      - ./env/common-environment.env
      - ./env/zipkin.env
    ports:
      - 9411:9411
    depends_on:
      - rabbitmq
    restart: always
  #nginx: 做反向代理，避免太多的端口导致混淆
  nginx:
    image: nginx:1.16
    container_name: supermap.nginx
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/static:/usr/share/nginx/html
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    env_file:
      - ./env/common-environment.env
    ports:
      - 8080:80
      - 8086:8086
    restart: always
networks:
  default:
    external:
      name: one-window
volumes:
  mysql_master_data:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local

