version: "3.6"
services:
  spring-boot-admin-server:
    image: spring-boot-admin-server
    container_name: spring-boot-admin-server
    restart: on-failure
    build:
      context: ../application/spring-boot-admin-server
      dockerfile: Dockerfile
    ports:
      - "8770:8770"
    extra_hosts:
      - "onewindow:114.67.110.209"
      - "nacos:114.67.110.209"
    volumes:
      - ./logs:/home/log
  business-ow-api-mianyang:
    image: business-ow-api-mianyang
    container_name: business-ow-api-mianyang
    restart: on-failure
    build:
      context: ../application/business-ow-api-mianyang
      dockerfile: Dockerfile
    ports:
      - "8768:8768"
    extra_hosts:
      - "onewindow:114.67.110.209"
      - "nacos:114.67.110.209"
    volumes:
      - ./logs:/home/log
  business-bdck-search-server:
    image: business-bdck-search-server
    container_name: business-bdck-search-server
    restart: on-failure
    build:
      context: ../application/business-bdck-search-server
      dockerfile: Dockerfile
    ports:
      - "8771:8771"
    extra_hosts:
      - "onewindow:114.67.110.209"
      - "nacos:114.67.110.209"
      - "cdserver:182.138.102.61"
    volumes:
      - ./logs:/home/log
networks:
  default:
    external:
      name: one-window