# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  scrape_timeout: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.
  evaluation_interval: 15s
# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  # 默认的自带监控
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 172.17.0.1:9090
  # docker 容器的监控
  - job_name: docker
    static_configs:
      - targets:
          - 172.17.0.1:9110
  # 主机监控
  - job_name: node
    static_configs:
      - targets:
          - 172.17.0.1:9100