version: '3'

services:
  zipkin:
    image: openzipkin/zipkin:2.18
    container_name: zipkin
    ports:
      - 9411:9411
    environment:
      - RABBIT_ADDRESSES=rabbitmq
      - RABBIT_USER=rabbitmq
      - RABBIT_PASSWORD=rabbitmqpassword
      - STORAGE_TYPE=elasticsearch
      # Point the zipkin at the storage backend
      # - ES_HOSTS=elasticsearch
      - ES_HOSTS=elasticsearch:9200
      # Uncomment to see requests to and from elasticsearch
      # - ES_HTTP_LOGGING=BODY
      - ES_HTTP_LOGGING=BASIC
    networks:
      - elasticsearch
      - rabbitmq
networks:
  elasticsearch:
    external:
      name: elasticsearch
  rabbitmq:
    external:
      name: rabbitmq