version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    privileged: true
    environment:
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmqpassword'
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - rabbitmq
networks:
  rabbitmq:
    external:
      name: rabbitmq