version: '2'
# 绵阳一窗受理项目，日志收集环境的部署
services:
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: reg.chiq-cloud.com/arm64v8/graylog:3.1.3
    container_name: supermap.garylog
    networks:
      - one-window
    volumes:
      # - graylog_data:/usr/share/graylog/data/journal
      - graylog_data:/usr/share/graylog/data
      - /home/docker/supermap_onewindow/config/graylog:/usr/share/graylog/data/config
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      # 这个地址需要配置成你要访问的地址，比如你的容器部署在192.168.1.2，你需要配置成http://192.168.1.2:9000/api，否则访问会报错
      - GRAYLOG_HTTP_EXTERNAL_URI=http://172.253.1.20:9000/
      # 时区
      - TZ=Asia/Shanghai
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    restart: always
  # cadvisor: https://hub.docker.com/r/google/cadvisor
  cadvisor:
    image: reg.chiq-cloud.com/arm64v8/cadvisor:v0.34.0
    container_name: supermap.cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /cgroup:/cgroup:ro
    privileged: true
    networks:
      - one-window
    #detach: true
    # 注意这儿配置的是 influxdb 的连接参数
    command: -storage_driver=influxdb -storage_driver_host=172.17.0.1:8286 -storage_driver_db=monitor -storage_driver_user=monitor -storage_driver_password=monitorpassword
    ports:
      - 8180:8080
    restart: always
  # grafana: https://hub.docker.com/r/grafana/grafana
  grafana:
    image: reg.chiq-cloud.com/arm64v8/grafana:6.3.5
    container_name: supermap.grafana
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - one-window
    ports:
      - 3000:3000
    restart: always
  # nacos：https://hub.docker.com/r/nacos/nacos-server
  nacos:
    image: reg.chiq-cloud.com/arm64v8/nacos-server:1.1.3
    container_name: supermap.nacos
    environment:
      - TZ=Asia/Shanghai
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_MASTER_SERVICE_HOST=172.17.0.1
      - MYSQL_MASTER_SERVICE_DB_NAME=nacos_config
      - MYSQL_MASTER_SERVICE_PORT=3306
      - MYSQL_SLAVE_SERVICE_HOST=172.17.0.1
      - MYSQL_SLAVE_SERVICE_PORT=3306
      - MYSQL_MASTER_SERVICE_USER=root
      - MYSQL_MASTER_SERVICE_PASSWORD=eVoATqQM1VL4ysos
    volumes:
      - /home/docker/supermap_onewindow/logs/nacos/:/home/nacos/logs
      - /home/docker/supermap_onewindow/config/nacos/nacos-custom.properties:/home/nacos/init.d/custom.properties
    networks:
      - one-window
    ports:
      - 8848:8848
      - 9555:9555
    restart: always
  #sentinel-dashboard：https://hub.docker.com/r/bladex/sentinel-dashboard
  sentinel-dashboard:
    image: reg.chiq-cloud.com/arm64v8/sentinel-dashboard:1.7.0
    container_name: supermap.sentinel-dashboard
    volumes:
      - /home/docker/supermap_onewindow/logs/sentinel:/root/logs
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Dserver.port=8080 -Dcsp.sentinel.dashboard.server=localhost:8080 -Dproject.name=sentinel-dashboard -Djava.security.egd=file:/dev/./urandom -Dcsp.sentinel.api.port=8718 -Dsentinel.dashboard.auth.username=sentinel -Dsentinel.dashboard.auth.password=sentinel
    networks:
      - one-window
    ports:
      - 8858:8080
      - 8719:8719
      - 8718:8718
    restart: always
  #elasticsearch-hd
  elasticsearch-hd:
    image: reg.chiq-cloud.com/arm64v8/elastichd:6.4
    container_name: supermap.elasticsearch-hd
    environment:
      - TZ=Asia/Shanghai
    networks:
      - one-window
    ports:
      - 9800:9800
    restart: always
  #zipkin
  zipkin:
    image: reg.chiq-cloud.com/arm64v8/zipkin:2.15.0
    container_name: supermap.zipkin
    environment:
      - RABBIT_ADDRESSES=172.17.0.1
      - RABBIT_USER=rabbitmq
      - RABBIT_PASSWORD=rabbitmqpassword
      - STORAGE_TYPE=elasticsearch
        #ES_HOSTS=${DOCKER_LOCAL_HOST}:9200
      - ES_HOSTS=172.17.0.1:9200
      - ES_HTTP_LOGGING=BASIC
      - TZ=Asia/Shanghai
    networks:
      - one-window
    ports:
      - 9411:9411
    restart: always
  #nginx: 做反向代理，避免太多的端口导致混淆
  nginx:
    image: reg.chiq-cloud.com/arm64v8/nginx:1.16
    container_name: supermap.nginx
    volumes:
      - /home/docker/supermap_onewindow/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/docker/supermap_onewindow/config/nginx/static:/usr/share/nginx/html
      - /home/docker/supermap_onewindow/config/nginx/conf.d:/etc/nginx/conf.d
      - /home/docker/supermap_onewindow/logs/nginx:/var/log/nginx
    networks:
      - one-window
    environment:
      - TZ=Asia/Shanghai
    ports:
      - #多开放几个端口，在网闸
      - 80:80
      - 8068:8082
      - 8086:8082
      - 8082:8082
      - 8083:8082
      #江油测试数据库，反向代理江油数据库
      - 9721:9721
    restart: always
networks:
  one-window:
    external:
      name: one-window
volumes:
  graylog_data:
    external: true
  grafana_data:
    external: true